version: '3.8'

services:
  splendor-postgres:
    image: postgres:latest
    container_name: splendor-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=splendor
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  splendor-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: splendor-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Splendor!123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: always

volumes:
  postgres-data:
    external: true
    name: splendor_postgres-data
  sqlserver-data:
    external: true
    name: splendor_sqlserver-data
